<?php

namespace Database\Seeders;

use App\Models\Content;
use App\Models\Module;
use App\Models\User;
use App\Services\ContentFormatter;
use Illuminate\Database\Seeder;

class ImportStructuredContentSeeder extends Seeder
{
    private ContentFormatter $formatter;

    public function run(): void
    {
        $this->formatter = new ContentFormatter();
        
        $admin = User::where('role', 'super_admin')->first();
        if (!$admin) {
            $this->command->error('No super admin found');
            return;
        }

        $this->command->info('📚 Seeding Structured Content...');

        $contents = $this->getContentMapping();
        $total = 0;

        foreach ($contents as $moduleName => $contentItems) {
            $module = Module::where('name', $moduleName)->first();
            if (!$module) {
                $this->command->warn("⚠ Module not found: {$moduleName}");
                continue;
            }

            foreach ($contentItems as $title => $lines) {
                $this->createFormattedContent($module, $title, $lines, $admin);
                $total++;
            }
        }

        $this->command->info("✅ Content seeding completed! (Total: {$total} items)");
    }

    private function getContentMapping(): array
    {
        return [
            'Tugas & Tanggung Jawab HRD' => [
                'Tugas & Tanggung Jawab HRD' => [
                    'General Responsibility',
                    'Merekrut dan menyeleksi talenta terbaik untuk organisasi',
                    'Mengembangkan program pelatihan dan pengembangan karyawan',
                    'Mengelola peraturan dan kebijakan kepegawaian',
                    'Menangani kompensasi, benefit, dan payroll',
                    'Menciptakan budaya kerja yang positif dan produktif',
                    'Menangani employee relations dan conflict resolution',
                    'Memastikan kepatuhan terhadap hukum ketenagakerjaan',
                ],
            ],
            'Struktur Organisasi' => [
                'Struktur Organisasi Perusahaan' => [
                    'Organisasi dipimpin oleh General Manager',
                    'HRD Department bertugas mengelola:',
                    '• Rekrutmen dan Seleksi',
                    '• Training & Development',
                    '• Employee Relations',
                    '• Payroll & Compensation',
                    'Hierarchy:',
                    'General Manager',
                    '└─ HRD Manager',
                    '   └─ HRD Staff',
                    '   └─ Training Officer',
                ],
            ],
            'Prosedur Absen' => [
                'Prosedur Absen' => [
                    'Tiga tipe absen berlaku:',
                    '',
                    '1. Partimer / Freelance',
                    'Absen dilakukan setiap hari dengan form manual',
                    'Verifikasi oleh supervisor terkait',
                    'Proses pembayaran based on hours worked',
                    '',
                    '2. Staff Level',
                    'Absen digital via aplikasi internal',
                    'Jam kerja: 08:00 - 17:00 WIB',
                    'Toleransi keterlambatan: 10 menit',
                    'Lembur harus pre-approval dari manager',
                    '',
                    '3. Supervisor Level',
                    'Absen digital dengan responsibilities khusus',
                    'Harus hadir 15 menit sebelum jam kerja',
                    'Bertanggung jawab verifikasi absen staff',
                    '',
                    '4. Manager Level',
                    'Absen digital dengan tracking khusus',
                    'Flexible working hours dengan approval',
                    'Bertanggung jawab oversight seluruh unit',
                ],
            ],
            'Prosedur Cuti & Izin' => [
                'Prosedur Cuti & Izin' => [
                    'Aturan Pengajuan Cuti:',
                    '1. Cuti tahunan berjumlah 12 hari kerja',
                    '2. Pengajuan minimal 7 hari sebelumnya',
                    '3. Persetujuan dari manager langsung',
                    '4. Backup harus tersedia sebelum cuti',
                    '',
                    'Jenis Izin:',
                    '• Izin Sakit: surat dokter untuk >2 hari',
                    '• Izin Pribadi: max 3 hari per tahun',
                    '• Izin Haji/Umroh: per kebijakan perusahaan',
                    '• Izin Menikah: 3 hari kerja',
                    '',
                    'Form:',
                    'Download form di portal internal',
                    'Lengkapi dan submit ke HRD',
                    'Proses: 1x24 jam',
                ],
            ],
            'Sanksi' => [
                'Sistem Demerit untuk Pelanggaran' => [
                    'Sistem Demerit untuk Pelanggaran:',
                    '',
                    'Kategori Ringan (1-5 demerit):',
                    '• Keterlambatan 15-30 menit',
                    '• Berpakaian tidak sesuai SOP',
                    '• Tidak melengkapi dokumentasi',
                    '',
                    'Kategori Sedang (6-15 demerit):',
                    '• Keterlambatan >30 menit',
                    '• Tidak masuk tanpa pemberitahuan',
                    '• Performa kerja di bawah standar',
                    '',
                    'Kategori Berat (>15 demerit):',
                    '• Pencurian / hal kriminal',
                    '• Tidak mengikuti SOP kritis',
                    '• Konflikt dengan tim / harassment',
                    '• Pelanggaran berulang',
                    '',
                    'Konsekuensi:',
                    'Demerit < 5: Warning',
                    'Demerit 5-10: Suspension 1-3 hari',
                    'Demerit > 10: Possible termination',
                ],
            ],
            'Prosedur Pengunduran Diri & Off Boarding' => [
                'Prosedur Pengunduran Diri & Off Boarding' => [
                    'Proses Pengunduran Diri:',
                    '1. Submit resignation letter minimal 2 minggu sebelumnya',
                    '2. Pindahkan tanggung jawab kepada replacement',
                    '3. Knowledge transfer session',
                    '4. Collect semua company assets',
                    '5. Final meeting dengan HRD',
                    '',
                    'Off Boarding Checklist:',
                    '• Collect ID card, access key, laptop',
                    '• Update sistem untuk access removal',
                    '• Final salary settlement',
                    '• Release reference letter',
                    '• Dokumentasi final evaluation',
                    '',
                    'Exit Interview:',
                    'Conducted oleh HRD Manager',
                    'Gather feedback untuk improvement',
                    'Maintain relationship untuk future opportunities',
                ],
            ],
            'Manajemen Kandidat Karyawan' => [
                'Prosedur Rekrutmen' => [
                    'Prosedur Rekrutmen:',
                    '',
                    'SLA HRD: 30 hari dari job open hingga hire',
                    '',
                    'Tahapan:',
                    '1. HR screening - 3 hari',
                    '2. Technical test - 2 hari',
                    '3. Manager interview - 3 hari',
                    '4. General Manager approval - 2 hari',
                    '5. Offer & negotiation - 5 hari',
                    '6. Onboarding - 7 hari',
                    '',
                    'Terminasi Kandidat:',
                    'Jika tidak lulus tahapan tertentu, komunikasi immediate',
                    'Keep databank untuk future opportunities',
                    '',
                    'Poin & KPI:',
                    'Target hire: 90% of open positions dalam 30 hari',
                    'Employee retention rate: 85%',
                    'Time-to-productivity: 30 hari',
                ],
            ],
            'Prosedur Seragam & Berbusana' => [
                'Panduan Dress Code' => [
                    'Dress Code - Office:',
                    '• Business casual untuk hari kerja normal',
                    '• Formal atau branded polo untuk meeting',
                    '• Closed shoes (tidak sandal)',
                    '• Rapi dan profesional',
                    '',
                    'Dress Code - Central Kitchen:',
                    '• Chef uniform (white)',
                    '• Non-slip shoes',
                    '• Hair net dan apron',
                    '• Name badge di dada',
                    '',
                    'Dress Code - Store:',
                    '• Branded polo / uniform terkait brand',
                    '• Black pants rapi',
                    '• Closed shoes (clean & polished)',
                    '• Name badge positioned',
                    '',
                    'Alokasi Seragam:',
                    'Baru hire: 3 set seragam',
                    'Replacement: Submit ke GA dengan bukti rusak',
                    'Penggantian tahunan: sesuai kondisi',
                ],
            ],
            'Tugas & Tanggung Jawab GA' => [
                'Tugas & Tanggung Jawab GA' => [
                    'General Affair (GA) Department bertanggung jawab:',
                    '',
                    '1. Facility Management',
                    'Pemeliharaan building dan equipment',
                    'Koordinasi vendor & contractor',
                    '',
                    '2. Asset Management',
                    'Tracking semua company assets',
                    'Maintenance schedule',
                    'Depreciation calculation',
                    '',
                    '3. Logistik & Supplies',
                    'Office supplies procurement',
                    'Distribution ke departemen',
                    'Inventory management',
                    '',
                    '4. Administrative Support',
                    'Dokumen & filing',
                    'Permit & licensing',
                    'External coordination',
                ],
            ],
            'Prosedur Pemeliharaan Aset' => [
                'Prosedur Pemeliharaan Aset' => [
                    'Store Maintenance:',
                    '',
                    'Aset:',
                    '• Monthly inspection',
                    '• Quarterly maintenance',
                    '• Replace jika rusak > 30%',
                    '',
                    'Bangunan:',
                    '• Weekly cleaning',
                    '• Monthly pest control',
                    '• Roof inspection setiap 6 bulan',
                    '',
                    'Taman / Outdoor:',
                    '• Weekly trimming & cleaning',
                    '• Monthly landscape maintenance',
                    '',
                    'Office & Central Kitchen Aset:',
                    '• AC maintenance: setiap 3 bulan',
                    '• Freezer maintenance: setiap bulan',
                    '• Equipment servicing: per manual',
                    '',
                    'Kendaraan:',
                    '• Oil change: setiap 5000 km',
                    '• Maintenance: setiap 10000 km',
                    '• Insurance & registration update',
                    '',
                    'Staff Level:',
                    '• Laptop: anti-virus update, disk cleanup',
                    '• Mouse/peripherals: replace if broken',
                    '• Phone: screen protector, case provided',
                ],
            ],
            'Pengajuan Perbaikan Aset & Bangunan' => [
                'Proses Pengajuan Perbaikan' => [
                    'Proses Pengajuan:',
                    '',
                    'Step 1: Identifikasi masalah',
                    'Step 2: Fill form (download dari portal)',
                    'Step 3: Submit ke GA Manager',
                    'Step 4: GA assess & quotation',
                    'Step 5: Approval dari General Manager',
                    'Step 6: Eksekusi maintenance',
                    '',
                    'Timeline:',
                    'Emergency (critical): ASAP',
                    'High priority: 3 hari',
                    'Normal: 1 minggu',
                    'Low priority: 2 minggu',
                ],
            ],
            'Prosedur Perjalanan Dinas' => [
                'Prosedur Perjalanan Dinas' => [
                    'Proses Perjalanan Dinas:',
                    '',
                    '1. Buat travel request dengan detail',
                    '2. Submit untuk approval (min 7 hari sebelumnya)',
                    '3. Booking oleh GA atau finance',
                    '4. Dapatkan konirmasi booking',
                    '5. Travel dan collect receipt',
                    '6. Submit reimbursement dalam 3 hari',
                    '',
                    'Budget Allowance:',
                    '• Domestik: Rp500k - Rp1.5jt (tergantung kota)',
                    '• ASEAN: USD 100 - 200',
                    '• Internasional: USD 200+',
                    '',
                    'Reimbursement:',
                    'Proses: 1-2 minggu',
                    'Dokumen: receipt asli + form',
                ],
            ],
            'Marketing Department' => [
                'Marketing Department Overview' => [
                    'Team Marketing Overview',
                    '',
                    'Marketing Department fokus pada:',
                    '',
                    '1. Brand Awareness',
                    'Social media campaigns',
                    'Event & sponsorship',
                    'PR & media relations',
                    '',
                    '2. Product Promotion',
                    'Launch campaigns',
                    'Promotional strategy',
                    'Marketing materials',
                    '',
                    '3. Customer Engagement',
                    'CRM management',
                    'Newsletter & communication',
                    'Loyalty programs',
                    '',
                    'Key Functions:',
                    '• Strategy & planning',
                    '• Creative team (design, content)',
                    '• Digital marketing',
                    '• Analytics & reporting',
                ],
            ],
            'SOP Marketing' => [
                'SOP Marketing' => [
                    'Prosedur Sosialisasi Program Marketing:',
                    '',
                    '1. Campaign Planning',
                    'Brief dari management',
                    'Strategy meeting',
                    'Approve final concept',
                    '',
                    '2. Creative Development',
                    'Design stage:',
                    '• Mockup & iteration',
                    '• Stakeholder review',
                    '• Final approval',
                    '',
                    '3. Campaign Execution',
                    'Launch on schedule',
                    'Monitor performance',
                    'Daily engagement tracking',
                    '',
                    'Ruang Lingkup Marketing untuk Store:',
                    '• Local activation & events',
                    '• In-store promotional materials',
                    '• Community engagement',
                    '• Sales coordination',
                ],
            ],
            'Prosedur Permintaan Design kepada Marketing' => [
                'Permintaan Design' => [
                    'Cara Meminta Design ke Marketing:',
                    '',
                    '1. Submit Request',
                    'Fill form dengan detail:',
                    '• What (jenis design)',
                    '• Why (purpose)',
                    '• When (deadline)',
                    '• Details (specification)',
                    '',
                    '2. Marketing Brief',
                    'Meeting untuk clarify requirement',
                    'Define dimension, format, style',
                    '',
                    '3. Design Process',
                    'Initial concept: 2-3 hari',
                    'Revision: sesuai feedback',
                    'Final delivery: after approval',
                    '',
                    'Timeline:',
                    'Simple design: 3-5 hari',
                    'Complex design: 7-10 hari',
                    '',
                    'Note:',
                    'Rush order (+50% timeline)',
                    'Submit 1-2 minggu sebelumnya ideal',
                ],
            ],
            'Prosedur Finance' => [
                'Prosedur Finance' => [
                    'Pengajuan Pembayaran:',
                    '',
                    '1. Vendor creates invoice',
                    '2. Department head reviews & approves',
                    '3. Finance verifies amount & attachment',
                    '4. General Manager signs off',
                    '5. Payment processing',
                    '',
                    'Timeline:',
                    '• Invoice received → processed 3-5 hari',
                    '• Payment transfer: 1-2 hari kerja',
                    '',
                    'Proses Pelaporan Sales:',
                    '',
                    '1. Store submits daily sales report',
                    '2. Finance consolidate all sales',
                    '3. Generate management report',
                    '4. Monthly financial statement',
                    '5. Board reporting',
                    '',
                    'Requirements:',
                    '• Accuracy of data entry',
                    '• Supporting documents attached',
                    '• Timely submission',
                ],
            ],
            'Prosedur Accounting' => [
                'Pengurusan Pajak & Expense' => [
                    'Proses Pengurusan Pajak:',
                    '',
                    '1. PPh (Income Tax)',
                    '• Calculation monthly',
                    '• Payment: sebelum tgl 10 bulan berikutnya',
                    '• Annual settlement: March',
                    '',
                    '2. PPN (VAT)',
                    '• Input tracking',
                    '• Output tracking',
                    '• Monthly filing',
                    '',
                    '3. Withholding Tax',
                    '• Contractor & freelancer',
                    '• Foreign transactions',
                    '',
                    'CAPEX vs OPEX:',
                    '',
                    'CAPEX Definition:',
                    'Capital expenditure for assets > Rp5jt dengan useful life > 1 tahun',
                    '',
                    'OPEX Definition:',
                    'Operating expense untuk day-to-day business operations',
                    '',
                    'Approval Levels:',
                    '• CAPEX < Rp50jt: Manager',
                    '• CAPEX Rp50-200jt: Director',
                    '• CAPEX > Rp200jt: Board',
                    '• OPEX < Rp25jt: Manager',
                    '• OPEX Rp25-100jt: Director',
                    '• OPEX > Rp100jt: Board',
                ],
            ],
            'Prosedur Purchasing' => [
                'Prosedur Purchasing' => [
                    'Proses Pengajuan Barang dan Jasa:',
                    '',
                    '1. Department submits PO (Purchase Order)',
                    '2. Procurement verify quantity & specification',
                    '3. Send RFQ to 3 vendors minimum',
                    '4. Compare quotation & select best',
                    '5. Create PO & send to vendor',
                    '6. Follow up delivery',
                    '7. Receive goods & verify with PO',
                    '8. AP process invoice',
                    '',
                    'Timeline:',
                    '• Standart barang: 1-2 minggu',
                    '• Custom barang: 2-4 minggu',
                    '• Emergency order: negotiate with vendor',
                    '',
                    'Proses Pengajuan Barang Baru:',
                    '• Submit product sample + spec',
                    '• Quality & price evaluation',
                    '• Approval meeting',
                    '• Once approved: add to approved vendor list',
                    '• Ongoing replenishment via standart PO',
                ],
            ],
            'Produksi Dept' => [
                'Produksi Department Overview' => [
                    'Produksi Department Overview',
                    '',
                    'Team:',
                    '• Produksi Manager',
                    '• Assistant Manager',
                    '• Production Staff',
                    '• Quality Control',
                    '',
                    'Responsibility:',
                    '1. Gelato production',
                    '2. Drink production',
                    '3. Quality assurance',
                    '4. Inventory management',
                    '5. Compliance dengan food safety',
                    '',
                    'Key Success Factor:',
                    '• Tepat waktu production',
                    '• Konsisten kualitas',
                    '• Mengikuti food safety standards',
                    '• Inventory accuracy',
                ],
                'Inventory Produksi - Gelato' => [
                    'Alur Kerja Produksi Gelato:',
                    '',
                    '1. Receive formula & ingredient list',
                    '2. Pre-production check (ekspirasi, quality)',
                    '3. Mixing & processing',
                    '4. Cooling phase',
                    '5. Churning & freezing',
                    '6. Packaging',
                    '7. QC check',
                    '8. Freeze storage',
                    '9. Distribution',
                    '',
                    'Aturan Produksi:',
                    '• Hygiene: hand wash, glove, hair net mandatory',
                    '• Temperature control: -18C terjaga',
                    '• Traceability: batch number semua produk',
                    '• Cross-contamination: prevent allergen mix',
                    '',
                    'Deadline:',
                    '• Daily production: 06:00 - 14:00',
                    '• Packing: 14:00 - 16:00',
                    '',
                    'Quality Control:',
                    '• Taste & texture check setiap batch',
                    '• Expire date labeling',
                    '• Storage temperature verify',
                    '• Weekly shelf-life test',
                ],
                'Do & Dont\'s Produksi' => [
                    'DO:',
                    '✓ Wear complete safety gear (glove, apron, net)',
                    '✓ Wash hands before & after each task',
                    '✓ Follow recipe & measurement exactly',
                    '✓ Check expiry date sebelum use',
                    '✓ Report equipment issue immediately',
                    '✓ Maintain cleanliness work area',
                    '',
                    'DON\'T:',
                    '✗ Work when sick',
                    '✗ Eat/drink near production area',
                    '✗ Skip quality check step',
                    '✗ Use expired ingredients',
                    '✗ Leave equipment running unattended',
                    '✗ Mix batches dari different dates',
                ],
            ],
            'Packing Dept' => [
                'Packing Department Overview' => [
                    'Packing Team Overview',
                    '',
                    'Team Structure:',
                    '• Packing Manager',
                    '• Packing Supervisor',
                    '• Packing Staff (3-5 orang)',
                    '',
                    'Responsibility:',
                    '• Receive finish product dari produksi',
                    '• Packaging sesuai standard',
                    '• Quality inspection',
                    '• Labeling dengan correct info',
                    '• Organize for shipment',
                    '',
                    'Working Hours:',
                    '• Shift: 14:00 - 22:00 atau 10:00 - 18:00',
                    '• Daily target: 500-800 unit',
                ],
                'Alur Proses Packing' => [
                    'Alur Kerja Packing:',
                    '',
                    '1. Receive product list & specification',
                    '2. Pick product dari cooling room',
                    '3. Arrange dalam packaging material',
                    '4. Seal packaging (machine/manual)',
                    '5. Weigh & verify correct quantity',
                    '6. Apply label dengan info lengkap',
                    '7. QC final check',
                    '8. Organize box untuk shipment',
                    '9. Record & documentation',
                    '',
                    'QC Checklist:',
                    '• Random check 5% dari batch',
                    '• Verify seal integrity',
                    '• Check label accuracy',
                    '• Weight compliance',
                ],
                'Do & Dont\'s Packaging' => [
                    'DO:',
                    '✓ Use designated packaging material',
                    '✓ Maintain cold chain (keep <-18C)',
                    '✓ Check label sebelum apply',
                    '✓ Verify weight accuracy',
                    '',
                    'DON\'T:',
                    '✗ Use damaged packaging',
                    '✗ Leave packed product at room temperature',
                    '✗ Mix products dari different batches',
                    '✗ Skip QC step',
                ],
            ],
            'Warehouse Dept' => [
                'Warehouse Department Overview' => [
                    'Warehouse Team:',
                    '',
                    'Key Responsibility:',
                    '• Receive finished goods',
                    '• Organize & store efficiently',
                    '• Manage inventory accuracy',
                    '• Fulfill store orders',
                    '• Maintain cold storage',
                    '• Track expiry date',
                    '',
                    'Key Focus:',
                    '• FIFO (First In First Out)',
                    '• Proper temperature (< -18C)',
                    '• Accurate inventory records',
                    '• Timely fulfillment',
                    '• Prevent spoilage',
                ],
                'Prosedur Pemesanan Barang' => [
                    'Prosedur Pemesanan:',
                    '',
                    '1. Store Manager submit order form',
                    '2. Warehouse Manager verify stock',
                    '3. Process order (pick, QC, pack)',
                    '4. Prepare delivery dengan cold transport',
                    '5. Delivery & receipt documentation',
                    '',
                    'Timeline:',
                    'Same-day order: fulfill within 24 hours',
                    'Advance order: fulfill sesuai tanggal request',
                ],
                'Do & Dont\'s Warehouse' => [
                    'DO:',
                    '✓ Check expiry date setiap receive',
                    '✓ Maintain temperature strict',
                    '✓ Organize FIFO sistem',
                    '✓ Keep inventory record updated',
                    '',
                    'DON\'T:',
                    '✗ Stack product above capacity',
                    '✗ Leave freezer door open lama',
                    '✗ Mix different batches',
                    '✗ Skip expiry date check',
                ],
            ],
            'Food & Pastry Dept' => [
                'Food & Pastry Department' => [
                    'Food & Pastry Team:',
                    '',
                    'Department Focus:',
                    '• Pastry & baked goods production',
                    '• Topping & filling creation',
                    '• Special recipe development',
                    '• Quality consistency',
                    '',
                    'Key Product:',
                    '• Pastry shells',
                    '• Toppings & sauces',
                    '• Cone & biscuit',
                    '• Seasonal specials',
                    '',
                    'Standard:',
                    '• Food safety compliance',
                    '• Recipe standardization',
                    '• Quality control rigorous',
                    '• Inventory tracking',
                ],
                'Prosedur Kerja' => [
                    'Alur Kerja Produksi:',
                    '',
                    '1. Receive formula & ingredient list',
                    '2. Pre-production setup',
                    '3. Mixing & preparation',
                    '4. Baking / cooking process',
                    '5. Cooling & conditioning',
                    '6. Packaging untuk packing dept',
                    '7. QC check hasil',
                    '',
                    'Working hours:',
                    '• Early shift: 04:00 - 12:00',
                    '• Afternoon: 11:00 - 19:00',
                    '',
                    'Quality standard:',
                    '• Taste consistency',
                    '• Texture uniformity',
                    '• Visual appearance',
                    '• Proper packaging',
                ],
                'Prosedur Pemesanan' => [
                    'Prosedur Pemesanan:',
                    '',
                    '1. Produksi / Warehouse submit order',
                    '2. Food & Pastry Manager review',
                    '3. Schedule production line',
                    '4. Produce sesuai schedule',
                    '5. Deliver & document',
                    '',
                    'Lead Time:',
                    'Standart item: 2-3 hari',
                    'Custom recipe: 5-7 hari development',
                    'Seasonal: advance order min 2 minggu',
                ],
            ],
            'Logistik Dept' => [
                'Logistik Department' => [
                    'Logistik Team:',
                    '',
                    'Responsibility:',
                    '• Coordinate product distribution',
                    '• Transport management',
                    '• Delivery schedule optimization',
                    '• Partner dengan courier/driver',
                    '• Track shipment status',
                    '',
                    'Working Area:',
                    '• Intra-warehouse logistics',
                    '• Store distribution',
                    '• Customer delivery',
                    '• Return goods handling',
                ],
                'Prosedur Logistik' => [
                    'Peraturan Dasar Logistik:',
                    '',
                    'Pre-Delivery:',
                    '• Verify temperature alat transportasi',
                    '• Check vehicle condition',
                    '• Confirm delivery route',
                    '• Brief driver tentang timeline',
                    '',
                    'During Delivery:',
                    '• Maintain cold chain',
                    '• Avoid unnecessary stops',
                    '• Protect product damage',
                    '• Document delivery',
                    '',
                    'Post-Delivery:',
                    '• Collect signed proof',
                    '• Record temperature log',
                    '• Report any issue immediately',
                    '• Vehicle cleanup & maintenance',
                ],
            ],
            'Prosedur Dasar' => [
                'Store Operation Framework' => [
                    'Store Operation Framework',
                    '',
                    'Partimer / Freelance Level:',
                    '• Basic counter service',
                    '• Product serving',
                    '• Cleaning duty',
                    '• Follow SOP strictly',
                    '• Report to supervisor',
                    '',
                    'Store Supervisor Level:',
                    '• Oversee daily operation',
                    '• Staff management & scheduling',
                    '• Quality assurance',
                    '• Inventory management',
                    '• Report to Store Manager',
                    '',
                    'Store Manager Level:',
                    '• Full store accountability',
                    '• P&L responsibility',
                    '• Marketing & promotion',
                    '• Staff development',
                    '',
                    'Manager Operation Level:',
                    '• Multi-store oversight',
                    '• Strategy execution',
                    '• Performance monitoring',
                    '• Regional coordination',
                ],
            ],
            'SOP Pelayanan' => [
                'Standard Pelayanan Pelanggan' => [
                    'Greeting (0-30 detik saat customer masuk):',
                    '• Sapa dengan ramah & senyum',
                    '• "Selamat datang di (brand)"',
                    '• Tanyakan apa yang dicari',
                    '',
                    'Product Knowledge:',
                    '• Pahami semua menu items',
                    '• Tahu ingredientnya',
                    '• Bisa rekomendasi',
                    '• Handle dietary question',
                    '',
                    'Ordering Process:',
                    '1. Listen carefully',
                    '2. Confirm order',
                    '3. Ulangi untuk avoid mistake',
                    '4. Process order dg cepat',
                    '',
                    'Payment:',
                    '• Clear harga komunikasi',
                    '• Bandingkan alternatif pembayaran',
                    '• Terima payment dengan senyum',
                    '• Give receipt & change tepat',
                    '',
                    'While Serving:',
                    '• Serve dengan presentation baik',
                    '• Eye contact & senyum',
                    '• "Terima kasih sudah datang"',
                    '• Tanya apakah ada yang perlu tambahan',
                    '',
                    'Finishing:',
                    '• "Kami tunggu Anda kembali"',
                    '• Bersihkan meja setelah pelanggan pergi',
                ],
            ],
            'SOP Opening & Closing Store' => [
                'Prosedur Opening & Closing' => [
                    'Prosedur Opening Store:',
                    '',
                    'Pre-Opening (30 menit sebelum):',
                    '1. Unlock & masuk semua area',
                    '2. Check suhu freezer (harus -18C)',
                    '3. Verifikasi product quality',
                    '4. Bersihkan semua counter & peralatan',
                    '5. Setup register & payment system',
                    '6. Check persediaan supplies',
                    '7. Briefing to staff tentang hari ini',
                    '8. Test POS system',
                    '',
                    'Opening:',
                    '9. Unlock pintu untuk customer',
                    '10. Welcome first customer dengan enthusiasm',
                    '',
                    'Prosedur Closing Store:',
                    '',
                    'During Last Hour:',
                    '• Inform customer "closing soon"',
                    '• Finish pending orders',
                    '• Stop accepting new order 15 min before close',
                    '',
                    'Closing:',
                    '1. Lock pintu (stop entry)',
                    '2. Close cash register',
                    '3. Count & reconcile cash',
                    '4. Deep clean equipment',
                    '5. Mop floors & disinfect',
                    '6. Check freezer temperature',
                    '7. Turn off semua equipment',
                    '8. Final security check',
                    '9. Lock pintu depan',
                ],
            ],
            'Prosedur Penanganan Komplain' => [
                'Handling Complaint' => [
                    'Level 1 - Front Line (Staff):',
                    '1. Dengarkan dengan penuh perhatian',
                    '2. Tunjukkan empati',
                    '3. Jangan argue atau defensive',
                    '4. Catat apa keluhan utama',
                    '5. Tawarkan solusi langsung',
                    '6. Jika tidak bisa resolve → escalate',
                    '',
                    'Level 2 - Supervisor:',
                    '7. Supervisor meet dengan customer',
                    '8. Review apa sudah dicoba',
                    '9. Offer additional remedy',
                    '10. Get customer contact info',
                    '11. Promise follow-up',
                    '',
                    'Penyelesaian:',
                    '• Resolve dalam 24 jam',
                    '• Give appropriate compensation',
                    '• Document resolution',
                    '• Follow-up call customer',
                    '',
                    'Prevention:',
                    '• Analyze root cause',
                    '• Implement corrective action',
                    '• Share learning dengan team',
                ],
            ],
            'Prosedur New Store Opening' => [
                'Grand Opening Procedures' => [
                    'Pre-Opening Planning (4-6 minggu):',
                    '• Verify lokasi & facility',
                    '• Ensure semua equipment arrived & installed',
                    '• Set up POS & payment system',
                    '• Training received (staff & manager)',
                    '• Supply chain ready',
                    '• Marketing campaign prepared',
                    '',
                    'Fase 2: Soft Opening (1 minggu sebelum):',
                    '• Limited hours operation',
                    '• Trained staff only',
                    '• Test all process & system',
                    '• Iron out operation issues',
                    '• Get feedback dari trial customer',
                    '',
                    'Fase 3: Grand Opening (Day 1):',
                    '• Full hours operation',
                    '• Official announcement',
                    '• Special promotion/discount',
                    '• VIP customer invited',
                    '• Media & influencer present',
                    '',
                    'Post-Opening (First 2 weeks):',
                    '• Monitor closely daily',
                    '• Staff supervision intensif',
                    '• Quick problem resolution',
                    '• Customer feedback collection',
                    '• Quality assurance strict',
                    '',
                    'Success Criteria:',
                    '• 80% customer satisfaction',
                    '• Zero operational issue',
                    '• Staff confidence in SOP',
                    '• Sales projection 80%+',
                ],
            ],
        ];
    }

    private function createFormattedContent(
        Module $module,
        string $title,
        array $lines,
        User $admin
    ): void {
        if (empty($lines)) {
            return;
        }

        $formatted = $this->formatter->format($lines);
        $wrappedHtml = $this->formatter->wrapContent($formatted, $title);

        $existing = Content::where('module_id', $module->id)
            ->where('title', $title)
            ->first();

        if ($existing) {
            $existing->update([
                'content' => $wrappedHtml,
                'updated_by' => $admin->id,
            ]);
            $this->command->line("    ✏️  {$title}");
        } else {
            Content::create([
                'module_id' => $module->id,
                'title' => $title,
                'content' => $wrappedHtml,
                'status' => 'publish',
                'created_by' => $admin->id,
            ]);
            $this->command->line("    ✅ {$title}");
        }
    }
}
